### ISSUE TITLE
Connection Reset by Peer for Apple Devices

### ISSUE THREAD

**Issue by wangjiangb** [Alkaid-Benetnash/EmuBTHID#8]
I followed the instruction, and I can see the window with "grab" message, but as soon as I press a key, it will have the following error message. Do you have any clue? 

```
Registered
waiting for connection
Control channel connected to 00:8A:76:80:4A:F1
Interrupt channel connected to 00:8A:76:80:4A:F1
Exposed : 1
Exit
Traceback (most recent call last):
  File "/home/jiang/code/EmuBTHID/main.py", line 233, in <module>
    Window(d).loop(bthid_srv.send)
  File "/home/jiang/code/EmuBTHID/main.py", line 141, in loop
    send_call_back(bytes(kbd_state))
  File "/home/jiang/code/EmuBTHID/BluetoothHID.py", line 85, in send
    self.cinter.send(bytes_buf)

Connection Reset by Peer.
```

**Comment by Alkaid-Benetnash** [comment]
This looks like the other side of the bluetooth connection (i.e. the side that trying to pair with this emulated bluetooth device) somehow closed the connection.
Do you have additional device to test? I am not sure which side to blame given the current information.

**Comment by b0o** [comment]
Same issue here. In my case, the target device is an iPad.

**Comment by Alkaid-Benetnash** [comment]
@b0o Can you isolate the problem? Like does your setup work with an android? I have not tested this program with any apple devices and from old days I have the impression that apple devices have always had compatibility issues with third-party bluetooth devices.

**Comment by kfatehi** [comment]
Cool project! I get the same error (using an iPhone). It works well on an Android. I am not sure how to debug the iPhone situation however, unfortunately.

```
python main.py
Registered
waiting for connection
Control channel connected to ...
Interrupt channel connected to ...
Exposed : 1
Exit
Traceback (most recent call last):
  File "/root/EmuBTHID/main.py", line 233, in <module>
    Window(d).loop(bthid_srv.send)
  File "/root/EmuBTHID/main.py", line 187, in loop
    send_call_back(bytes(mouse_state))
  File "/root/EmuBTHID/BluetoothHID.py", line 85, in send
    self.cinter.send(bytes_buf)
ConnectionResetError: [Errno 104] Connection reset by peer
```

**Comment by jal-frezie** [comment]
I now have the same issue, but with line numbers 232, 140 and 85 (presumably changing due to code version). 
My intended client is a Mac Mini M1.

[off-topic: there's no need to replace the X terminal with Tkinter as the current version will work fine with Wayland due to backward compatibility provided by Xwayland]

**Comment by justaCasualCoder** [comment]
Got this when trying to connect to a IPhone....
